steps:
  - id: Build
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |

        DOCKER_IMAGE=eu.gcr.io/$PROJECT_ID/cloudrun-example:$COMMIT_SHA
        docker build -t $$DOCKER_IMAGE .
        docker push $$DOCKER_IMAGE
  - id: Deploy
    name: 'gcr.io/cloud-builders/gcloud@sha256:9ceb8143f170d76de4b3ba7b35820c09a50336d6b378fe343eec883f37771167'
    entrypoint: /bin/bash
    args:
      - '-c'
      - |

        DOCKER_IMAGE=eu.gcr.io/$PROJECT_ID/cloudrun-example:$COMMIT_SHA

        # Deploy Cloud Run container
        gcloud beta --project=$PROJECT_ID run deploy \
        --platform managed \
        --image $$DOCKER_IMAGE \
        --region=europe-west1 \
        --allow-unauthenticated \
        cloudrun-example